apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "todo.fullname" . }}
  labels:
    tier: {{ .Values.tier }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
      tier: {{ .Values.tier }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        tier: {{ .Values.tier }}
    spec:
      volumes:
      - name: dir
        emptyDir: {}
      - name: nginx-confs
        configMap:
          name: nginx-conf
          items:
            - key: default.conf
              path: default.conf
      containers:
      - name: {{ Values.php.name }}
        image: "{{ .Values.php.repository }}:{{ .Values.php.tag }}"
        ports: 
          - containerPort: {{ .Values.php.port }}
        volumeMounts:
        - mountPath: /usr/share/nginx/todo
          name: dir
      - name: {{ Values.image.name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: {{ .Values.image.port }}
        volumeMounts:
          - name: dir
            mountPath: /usr/share/nginx/todo
          - name: nginx-confs
            mountPath: /etc/nginx/conf.d
#        livenessProbe:
#          httpGet:
#            path: /index.php
#            port: 8080
#          initialDelaySeconds: 3
#          periodSeconds: 3
      initContainers:
      - name: {{ Values.init.name }}
        image: "{{ .Values.init.repository }}:{{ .Values.init.tag }}"
        command: [ "sh", "-c" ]
        args: [ "cp -r /usr/share/nginx/todo/* /dir" ]
        volumeMounts:
        - name: dir
          mountPath: /dir
      imagePullSecrets:
      - name: gke-r
