apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo.fullname" . }}
  labels:
    tier: {{ .Values.tier }}
spec:
  selector:
    app: {{ .Values.app }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
