nginx:
  build: ./nginx/
  container_name: nginx-container
  ports:
   - 80:80
  links: 
   - php

php:
  build: ./php/
  container_name: php-container
  expose:
   - 9000
  links: 
   - mysql
  volumes:
   - /var/Test
   - ./www/Todo/:/var/www/Todo/
  
mysql: 
  image: mysql:8.0.27
  container_name: mysql-container
  command: --init-file /data/init.sql
  volumes:
   - ./init.sql:/data/init.sql
   - ./dbfile:/var/lib/mysql
  environment:
   MYSQL_USER: root
   MYSQL_PASSWORD: root
   MYSQL_DATABASE: todolist
  ports: 
   - 3308:3306

  
  
  
  
